version: "3.8"

services:
  reclamationdb:
    image: mysql:latest
    container_name: mysql_reclamation
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: adminer
      MYSQL_PASSWORD: root1
      MYSQL_DATABASE: reclamation
    ports:
      - '3307:3306'
    volumes:
      - db_reclamation_data:/var/lib/mysql

  phpmyadmin_reclamation:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_reclamation
    restart: always
    environment:
      PMA_HOST: reclamationdb
      PMA_USER: adminer
      PMA_PASSWORD: root1
    ports:
      - '8081:80'

  actualitedb:
    image: mysql:latest
    container_name: mysql_actualite
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: adminer
      MYSQL_PASSWORD: root1
      MYSQL_DATABASE: actualite
    ports:
      - '3308:3306'
    volumes:
      - db_actualite_data:/var/lib/mysql

  phpmyadmin_actualite:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_actualite
    restart: always
    environment:
      PMA_HOST: actualitedb
      PMA_USER: adminer
      PMA_PASSWORD: root1
    ports:
      - '8082:80'

  evenementdb:
    image: mysql:latest
    container_name: mysql_evenement
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: adminer
      MYSQL_PASSWORD: root1
      MYSQL_DATABASE: evenement
    ports:
      - '3309:3306'
    volumes:
      - db_evenement_data:/var/lib/mysql

  phpmyadmin_evenement:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_evenement
    restart: always
    environment:
      PMA_HOST: evenementdb
      PMA_USER: adminer
      PMA_PASSWORD: root1
    ports:
      - '8083:80'

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "9090:8080"
    command:
      - start-dev
      - --features=declarative-ui
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  db_reclamation_data:
  db_actualite_data:
  db_evenement_data:
  keycloak_data:
  azurite_data: